/**
 * db.ts
 * An in-memory SQLite mirror of the dataset, so the talk-to-data agent can answer with
 * real SQL instead of a hand-written query planner. The whole table is built once, lazily,
 * on the first runSql call and cached at module scope for the life of the process (so every
 * request reuses the same connection). It is rebuilt from src/data/dataset.json, which is
 * the single source of the rows; nothing here invents data.
 *
 * runSql is the only export the rest of the app uses. It NEVER throws: a bad or disallowed
 * query comes back as { rows: [], error }. The connection is locked read-only at several
 * layers (see runSql) so the agent cannot mutate anything even if it tries.
 */
import Database from "better-sqlite3";
import type { Transaction } from "./contract";
import dataset from "./../data/dataset.json";

// The dataset, typed. dataset.json is generated by scripts/preprocess.ts from the xlsx and
// is exactly Transaction[]; the double assertion sidesteps the giant JSON literal type.
const transactions = dataset as unknown as Transaction[];

/**
 * Maps every Transaction field to its SQL column name. Typed as Record<keyof Transaction,
 * string> on purpose: if a field is added to or renamed in the contract, this object stops
 * compiling until it is updated, so the SQL mirror can never silently drift from the type.
 * The SQL side uses snake_case (and the clearer merchant_* names) because the grounding
 * prompt and the ground-truth queries reference these exact column names.
 */
export const COLUMN_MAP: Record<keyof Transaction, string> = {
  id: "id",
  txnDate: "txn_date",
  postingDate: "posting_date",
  merchant: "merchant",
  description: "description",
  amount: "amount",
  direction: "direction",
  transactionCode: "transaction_code",
  lineType: "line_type",
  mcc: "mcc",
  category: "category",
  city: "merchant_city",
  state: "merchant_state",
  country: "merchant_country",
  isSpend: "is_spend",
  employeeId: "employee_id",
  department: "department",
};

// SQLite storage class per SQL column, keyed by the SQL name so it stays aligned with
// COLUMN_MAP. amount is REAL (it is summed/compared as money); is_spend is an INTEGER 1/0
// boolean; everything else is TEXT and may be NULL exactly as the contract allows.
const SQL_TYPES: Record<string, string> = {
  id: "TEXT",
  txn_date: "TEXT",
  posting_date: "TEXT",
  merchant: "TEXT",
  description: "TEXT",
  amount: "REAL",
  direction: "TEXT",
  transaction_code: "TEXT",
  line_type: "TEXT",
  mcc: "TEXT",
  category: "TEXT",
  merchant_city: "TEXT",
  merchant_state: "TEXT",
  merchant_country: "TEXT",
  is_spend: "INTEGER",
  employee_id: "TEXT",
  department: "TEXT",
};

// SQL column names in a stable order (the insertion order of COLUMN_MAP).
const SQL_COLUMNS = Object.values(COLUMN_MAP);

// One Transaction turned into a row keyed by SQL column name. The only non-direct mapping
// is the boolean isSpend, stored as 1/0 so `is_spend = 1` works in SQL; nulls pass through.
function toRow(txn: Transaction): Record<string, unknown> {
  return {
    id: txn.id,
    txn_date: txn.txnDate,
    posting_date: txn.postingDate,
    merchant: txn.merchant,
    description: txn.description,
    amount: txn.amount,
    direction: txn.direction,
    transaction_code: txn.transactionCode,
    line_type: txn.lineType,
    mcc: txn.mcc,
    category: txn.category,
    merchant_city: txn.city,
    merchant_state: txn.state,
    merchant_country: txn.country,
    is_spend: txn.isSpend ? 1 : 0,
    employee_id: txn.employeeId,
    department: txn.department,
  };
}

// Cached connection. Lazily created so the native binding never runs during `next build`,
// only at first use at runtime.
let cachedDb: Database.Database | null = null;

// Builds the in-memory table, seeds it, then locks it read-only.
function buildDb(): Database.Database {
  const db = new Database(":memory:");

  // Step 1: schema, derived from COLUMN_MAP + SQL_TYPES so the columns can never disagree.
  const columnDefs = SQL_COLUMNS.map((column) => `${column} ${SQL_TYPES[column]}`).join(", ");
  db.exec(`CREATE TABLE transactions (${columnDefs})`);

  // Step 2: one prepared insert with @named params, also derived from SQL_COLUMNS.
  const placeholders = SQL_COLUMNS.map((column) => `@${column}`).join(", ");
  const insert = db.prepare(`INSERT INTO transactions (${SQL_COLUMNS.join(", ")}) VALUES (${placeholders})`);

  // Step 3: seed every row inside a single transaction (orders of magnitude faster than
  // 4k individual inserts).
  const insertAll = db.transaction((rows: Transaction[]) => {
    for (const txn of rows) insert.run(toRow(txn));
  });
  insertAll(transactions);

  // Step 4: lock the connection to reads only. Set AFTER seeding so our own inserts run.
  // This is the engine-level backstop: even if a write somehow passed runSql's guards,
  // SQLite itself now rejects it.
  db.pragma("query_only = true");
  return db;
}

function getDb(): Database.Database {
  if (!cachedDb) cachedDb = buildDb();
  return cachedDb;
}

// The hard cap on returned rows, applied both as an appended LIMIT and a final slice.
const HARD_ROW_CAP = 500;

// Write/DDL/admin keywords that must never appear as a real statement keyword. Checked as
// whole words against a copy of the query with string literals masked out (see runSql), so
// a merchant literal like 'CREATE CORP' does not trip it but a real `DROP TABLE` does.
const FORBIDDEN_KEYWORDS = /\b(insert|update|delete|drop|alter|create|replace|vacuum|attach|detach|pragma|reindex|truncate|begin|commit|rollback)\b/i;

/**
 * Runs ONE read-only SQL statement and returns its rows. Never throws. On anything
 * disallowed or malformed, returns { rows: [], error } so the agent can read the error and
 * correct its SQL. The guards are layered on purpose (the prompt's rule: do not rely on a
 * keyword blocklist alone):
 *
 *   1. must be a non-empty string;
 *   2. exactly one statement (one optional trailing ; allowed, none in the middle);
 *   3. must start with SELECT or WITH (a read or a CTE);
 *   4. no write/DDL/PRAGMA keyword anywhere (checked with string literals masked out);
 *   5. a hard row cap appended when absent, and sliced as a backstop;
 *   6. the prepared statement must be a reader (returns rows), else it is rejected;
 *   7. the connection itself is query_only (engine-level refusal of writes).
 */
export function runSql(query: string): { rows: Record<string, unknown>[]; error?: string } {
  // Guard 1: a usable string.
  if (typeof query !== "string") return { rows: [], error: "Query must be a string." };
  let sql = query.trim();
  if (sql.length === 0) return { rows: [], error: "Empty query." };

  // Guard 2: a single statement. Drop one optional trailing semicolon, then reject any
  // remaining one (defends against stacked statements like "SELECT 1; DROP TABLE x").
  if (sql.endsWith(";")) sql = sql.slice(0, -1).trim();
  if (sql.includes(";")) return { rows: [], error: "Only a single SQL statement is allowed." };

  // Guard 3: reads only. The statement must begin with SELECT or WITH.
  if (!/^(select|with)\b/i.test(sql)) {
    return { rows: [], error: "Only SELECT or WITH (read-only) queries are allowed." };
  }

  // Guard 4: no write/DDL/admin keywords. Mask single-quoted string literals first ('' is
  // SQL's escaped quote) so the check looks only at SQL tokens, not at data values.
  const withoutStringLiterals = sql.replace(/'(?:[^']|'')*'/g, "''");
  if (FORBIDDEN_KEYWORDS.test(withoutStringLiterals)) {
    return { rows: [], error: "Only read-only queries are allowed (no INSERT/UPDATE/DELETE/DDL/PRAGMA)." };
  }

  // Guard 5: hard row cap. Append LIMIT when the query has no top-level LIMIT of its own,
  // so a bare `SELECT * FROM transactions` cannot dump all rows.
  if (!/\blimit\b/i.test(withoutStringLiterals)) sql = `${sql} LIMIT ${HARD_ROW_CAP}`;

  try {
    const statement = getDb().prepare(sql);
    // Guard 6: better-sqlite3 marks data-returning statements as readers; refuse anything
    // that is not (a non-reader here would be a write that slipped past the regex).
    if (!statement.reader) return { rows: [], error: "Query does not return rows." };

    const rows = statement.all() as Record<string, unknown>[];
    // Backstop slice in case the query carried its own larger LIMIT.
    return { rows: rows.slice(0, HARD_ROW_CAP) };
  } catch (err) {
    // Bad SQL (syntax, unknown column, query_only violation): hand the message back so the
    // agent can fix its query on the next loop turn.
    return { rows: [], error: err instanceof Error ? err.message : String(err) };
  }
}
